### PR TITLE
Print number

### LINKED ISSUE #568: Error: text must be a string or an object
Can you allow also numbers? Maybe just converted to string behind the scene?)

### PR DESCRIPTION
**Pull request by hipstersmoothie**
# What's Changing and Why

Allow print to print any type.

closes #568

## Tasks

- [x] Add tests
- [x] Update Documentation
- [x] Update `jimp.d.ts`
- [x] Add [SemVer](https://semver.org/) Label

### CODE REVIEW

File: packages/plugin-print/src/index.js [hunk 1]
```diff
@@ -263,13 +259,14 @@ export default () => ({
       let alignmentX;
       let alignmentY;
 
-      if (typeof text === 'object') {
+      if (typeof text === 'object' && text.text) {
```
Comment (edi9999) [inline packages/plugin-print/src/index.js]: I think it should be : 

```
      if (typeof text === 'object' && typeof text.text === "string") {
```

since we would want : {text:''} , to not error.

Comment (edi9999) [reply packages/plugin-print/src/index.js]: or maybe text.text != null

**Comment by hipstersmoothie** [comment]
@edi9999 I changed it it !== null so a user could still provide non string in the text object
